Casa-di-Roma/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Casa_di_Roma.Data;
using Casa_di_Roma.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Casa_di_Roma.Controllers
{
    public class CartController : Controller
    {

                private Casa_di_RomaDbContext context;

                public CartController(Casa_di_RomaDbContext dbContext)
                {
                        context = dbContext;
                }



                public IActionResult Index()
                {
                        Cart MyCart = new Cart
                        {
                                menuitems = Cart.GetAll()
                        };

                        return View(MyCart);
                }

                [HttpPost]
                public IActionResult Index(int newItem)
                {
                        Cart MyCart = new Cart
                        {
                                menuitems = Cart.GetAll()
                        };

                        MenuItem NewItem = context.MenuItems.Single(c => c.ID == newItem);
                      
                        foreach (MenuItem plate in MyCart.menuitems)
                        {
                                if (plate.ID == NewItem.ID)
                                {
                                        plate.Quantity++;
                                        Cart.Total += NewItem.Price;
                                        NewItem.Price += NewItem.Price;

                                        return View(MyCart);
                                }
                        }

                        Cart.Add(NewItem);

                        return View(MyCart);
                }


                [Route("Cart/Remove/{discard}")]
                public IActionResult Remove(int discard)
                {

                        MenuItem Olditem = Cart.GetById(discard);
                        int num = Olditem.Quantity;
                        double deduct = Olditem.Price * num;
                        Cart.Total -= deduct;
                        
                        Cart.Remove(discard);
                        


                        return Redirect("/Cart");
                }


        }
}

Casa-di-Roma/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Casa_di_Roma.Controllers
{
    public class LocationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Casa-di-Roma/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Casa di Roma</title>
    <link rel="shortcut icon" type="image/png" href="/images/favicon.png" />
    <!--4281 4333 3978 4207 boot-->
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://fonts.googleapis.com/css?family=Italiana|Playfair+Display+SC:700|Kreon:700|Thasadith:400i" rel="stylesheet">
        <script src='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
        <link href='https://api.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"></a>
                <img src="~/images/Casa logo.png" id="logo" />
                <img src="~/images/facebook.png" id="medialogo" />&nbsp;
                <p id="medialogo" ></p>
                <img src="~/images/instagram.png" id="medialogo" />
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="MainMenu">Main Menu</a></li>
                    <li><a asp-area="" asp-controller="Location" asp-action="Index">Locations</a></li>
                    <li><a asp-area="" asp-controller="Cart" asp-action="Index">Cart</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>

        </div>
        
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <!--<p>&copy; 2019 - Casa_di_Roma</p>-->
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>